<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Roank" failures="3" tests="4" name="Test" time="36.378" errors="0" timestamp="2025-07-26T22:17:52 IST">
  <testcase classname="testCases.TC003_LoginDatadrivenTest" name="dataDrivenTest" time="2.968"/>
  <testcase classname="testCases.TC003_LoginDatadrivenTest" name="dataDrivenTest" time="11.658">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDatadrivenTest.dataDrivenTest(TC003_LoginDatadrivenTest.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- dataDrivenTest -->
  <testcase classname="testCases.TC003_LoginDatadrivenTest" name="dataDrivenTest" time="11.318">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDatadrivenTest.dataDrivenTest(TC003_LoginDatadrivenTest.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- dataDrivenTest -->
  <testcase classname="testCases.TC003_LoginDatadrivenTest" name="dataDrivenTest" time="2.587">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDatadrivenTest.dataDrivenTest(TC003_LoginDatadrivenTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- dataDrivenTest -->
</testsuite> <!-- Test -->
